export const SUCCESS_BUY_DEVICE = "Товары успешно куплены"
export const SUCCESS_APPROVE_DEVICE = "Вы подтвердили получение товара"
export const SUCCESS_REFOUND_DEVICE = "Возврат суммы подтвержден"
export const CONFIRM_APPROVE_DEVICE = "Вы действительно подтверждаете, что получили товар"
export const CONFIRM_REFOUND_DEVICE = "Вы действительно подтверждаете, отмену заказа?"
