export {
	FIELD_REQUIRED,
	LOGIN_MAX_LENGTH,
	LOGIN_MIN_LENGTH,
	REGULAR_EMAIL,
	REGULAR_EMAIL_MESSAGE,
	PASSWORD_MAX_LENGTH,
	PASSWORD_MIN_LENGTH,
	REGULAR_PASSWORD,
	REGULAR_PASSWORD_MESSAGE
} from "./auth"
