import Head from "next/head"

import { Button } from "@/shared/ui/general/Button"
import { ButtonGroup } from "@/shared/ui/general/ButtonGroup"

const Home = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Button>CLICK</Button>
				<Button variant="contained">CLICK</Button>
				<Button variant="outlined">CLICK</Button>
				<ButtonGroup>
					<Button>CLICK</Button>
					<Button>CLICK</Button>
					<Button>CLICK</Button>
				</ButtonGroup>
				<ButtonGroup>
					<Button size="large" variant="outlined">
						CLICK
					</Button>
					<Button size="large" variant="outlined">
						CLICK
					</Button>
					<Button size="large" variant="outlined">
						CLICK
					</Button>
				</ButtonGroup>
				<ButtonGroup>
					<Button size="large" variant="contained">
						CLICK
					</Button>
					<Button size="large" variant="contained">
						CLICK
					</Button>
					<Button size="large" variant="contained">
						CLICK
					</Button>
				</ButtonGroup>
			</main>
		</>
	)
}

export default Home
