import Head from "next/head"

import { TextField } from "@/shared/ui/inputs/TextField/TextField"

const Home = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<TextField label="Label" subText="Sub text" />
			</main>
		</>
	)
}

export default Home
