export interface IUIColor {
	default_10: string
	default_20: string
	default_30: string
	default_40: string
	default_50: string
	default_60: string
	default_70: string
	default_80: string
	default_90: string
	default_100: string
	primary_10: string
	primary_20: string
	primary_30: string
	primary_40: string
	primary_50: string
	primary_60: string
	primary_70: string
	primary_80: string
	primary_90: string
	primary_100: string
	secondary_10: string
	secondary_20: string
	secondary_30: string
	secondary_40: string
	secondary_50: string
	secondary_60: string
	secondary_70: string
	secondary_80: string
	secondary_90: string
	secondary_100: string
	tertiary_10: string
	tertiary_20: string
	tertiary_30: string
	tertiary_40: string
	tertiary_50: string
	tertiary_60: string
	tertiary_70: string
	tertiary_80: string
	tertiary_90: string
	tertiary_100: string
	quaternary_10: string
	quaternary_20: string
	quaternary_30: string
	quaternary_40: string
	quaternary_50: string
	quaternary_60: string
	quaternary_70: string
	quaternary_80: string
	quaternary_90: string
	quaternary_100: string
	success_10: string
	success_20: string
	success_30: string
	success_40: string
	success_50: string
	success_60: string
	success_70: string
	success_80: string
	success_90: string
	success_100: string
	danger_10: string
	danger_20: string
	danger_30: string
	danger_40: string
	danger_50: string
	danger_60: string
	danger_70: string
	danger_80: string
	danger_90: string
	danger_100: string
	warning_10: string
	warning_20: string
	warning_30: string
	warning_40: string
	warning_50: string
	warning_60: string
	warning_70: string
	warning_80: string
	warning_90: string
	warning_100: string
}
