import Head from "next/head"
import { FC } from "react"
import styled from "styled-components"

const Wrapper = styled.div`
	height: 1000px;
`

export const HomeView: FC = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Wrapper></Wrapper>
		</>
	)
}
